# Generated by Django 5.2.8 on 2025-11-29 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_poliza'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Poliza',
            new_name='Pedido',
        ),
    ]
