# Generated by Django 5.2.8 on 2025-11-29 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poliza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pedido', models.CharField(max_length=50)),
                ('cliente_nombre', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=50)),
            ],
        ),
    ]
