# Generated by Django 5.2.8 on 2025-12-02 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_producto_sesionusuario_delete_logmensaje_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogMensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('telefono', models.CharField(max_length=20)),
                ('mensaje', models.TextField()),
            ],
        ),
    ]
